### ISSUE TITLE
Issues as discussed

### ISSUE THREAD

**Issue by CirrusTech** [mhartington/ion-md-input#1]
Hi Mike.

As we discussed, the 2 issues I'd like to report are:

1) The read me states that the module should be included as ion-md-input where the module is actually named ionMdInput.

2) The possible indexing issue with the elements that causes the placeholder to slide back down even after the user has entered text into the input.

Thanks for a great component though!

**Comment by mhartington** [comment]
Will work on tomorrow, thanks

**Comment by mhartington** [comment]
Just pushed an update for this, seems to work now. Can you please confirm

http://codepen.io/mhartington/pen/zxwOay
