### ISSUE TITLE
hightlight-color not working

### ISSUE THREAD

**Issue by archer3cl** [mhartington/ion-md-input#11]
Fresh installation of ionic + md-input. Loading the demo and add hightlight-color="assertive" to the input but its not coloring

![image](https://cloud.githubusercontent.com/assets/4583932/8896802/cf955572-33cc-11e5-8f8e-aecd4d3e52e7.png)

**Comment by mhartington** [comment]
Can you provide a codepen that demos the issue

**Comment by archer3cl** [comment]
I just installed the module and went to the demo. Just that. It would be pointless do a codepen =(

**Comment by mhartington** [comment]
Should be fixed now. Sorry about that!
