### ISSUE TITLE
applying  ng-model to 'ionMdInput' do not give value in controller's scope

### ISSUE THREAD

**Issue by mayurbaldha** [mhartington/ion-md-input#13]
applying ng-model to 

 <ion-md-input placeholder="Feedback"  type="text" ng-model="feedbackbox"></ion-md-input>

Now when i render as html  it renders as

<label class="item item-input item-md-label ng-valid" placeholder="From" type="text" ng-model="feedbackbox"><input type="text" class="md-input ng-valid ng-dirty ng-valid-parse used ng-touched" ng-model="feedbackbox"><span class="input-label">feedback</span><div class="hightlight hightlight-calm"></div></label>

so, the label & textbox both have same model name,
So, can't set value to textbox ??

**Comment by mhartington** [comment]
Can you provide an example? Also, are you using this from ionic material?

**Comment by mhartington** [comment]
Closing due to no response
