### ISSUE TITLE
Not working properly on IOS9

### ISSUE THREAD

**Issue by jp928** [mhartington/ion-md-input#16]
Not working properly on IOS device, but working fine on simulator.
The issue is caused by the css selector input:focus.
When UI has multiple ion-md-input and the keyboard shows up input:focus won't work anymore. 
After dismiss the keyboard, the selector works again.

**Comment by tmjam** [comment]
I am seeing this issue as well on IOS9.

**Comment by mhartington** [comment]
Hmm, alright, I will investigate.

**Comment by tmjam** [comment]
@mhartington  This seems to be fixed for me after the ionic update.

**Comment by jp928** [comment]
Which version you are working with?

**Comment by tmjam** [comment]
@jp928 v1.7.1

**Comment by jp928** [comment]
That's ionic CLI version. With all due respect, I don't think it will help.

**Comment by tmjam** [comment]
@jp928  May be then it is this patch that I used for other issues related to IOS9 did it https://gist.github.com/IgorMinar/863acd413e3925bf282c

**Comment by Zorgatone** [comment]
I have the same issue :disappointed:

**Comment by Zorgatone** [comment]
How about manually blurring the input another gets activated?

**Comment by jp928** [comment]
@Zorgatone 
I had move to https://github.com/zachsoft/Ionic-Material. If you just need the floating placeholder in the input checkout the way how they implement.

**Comment by Zorgatone** [comment]
I am using that materialdesign.com already xD, but there is where I found the link to this github on their example o.O

**Comment by jp928** [comment]
you are possibly using the older version, in the latest version the dependency on this has been removed.

**Comment by Zorgatone** [comment]
There isn't still much documentation there, is it very similar to this one here?

**Comment by jp928** [comment]
Sorry for misleading you. In my case, I just add class .item-floating-label in the label tag. So the whole thing is pretty simple:

<label class="item item-input item-floating-label">
                    <span class="input-label">First Name</span>
                    <input ng-model="AddVisitorModel.newVisitorData.firstname" name="firstname" type="text" placeholder="First Name" required>
                </label>

If you check the ionic.app.css, the css code in there is quite straightforward.

**Comment by mhartington** [comment]
Pulled the latest ionic code that includes the ios9 patch and everything is working fine for me. Please make sure you are include that patch. Closing this.
