### ISSUE TITLE
how can I change highlight-color?

### ISSUE THREAD

**Issue by maries-15** [mhartington/ion-md-input#17]
I want to change highlight-color for a custom one, don't use colors by default, I'd like to know, if this is possible.
Thank you

**Comment by mhartington** [comment]
The highlight property just takes whatever string you pass it and appends `highlight-` to it.

So you could do.

```
<ion-md-input highlight="myColor"></ion-md-input
```
Then create the following css

```
 .item-md-label .highlight-myColor {
    background: #ffffff 
}
```
Or what ever color you wanted.
