### ISSUE TITLE
Not working with ui-validate

### ISSUE THREAD

**Issue by evaflow** [mhartington/ion-md-input#18]
This is just a friendly suggestion for ion-md-input to support angular ui-validate .. Thank You for all your hardwork!

**Comment by evaflow** [comment]
how can i confirm passwords with ion-md-input?

**Comment by mhartington** [comment]
I honestly never considered any kind of validation when I made this. Feel free to hack it and submit a PR if you want to add it.

**Comment by evaflow** [comment]
it's working i'm not sure why i couldn't get it to work before but after some rest i reattempted my code and its working fine!
