### ISSUE TITLE
Label Value Below Text

### ISSUE THREAD

**Issue by JesusJoseph** [mhartington/ion-md-input#30]
Hi,
Thanks for creating a very good plugin for Ionic. 
I am new  to Ionic and I am creating a new App now
I want to show the label below the text that I am entering.
Is is possible to do with any configuration.

Thanks for your help

joseph

**Comment by mhartington** [comment]
Please see the readme.

https://github.com/mhartington/ion-md-input/blob/master/README.md

I am not maintaining this anymore
