### ISSUE TITLE
ng-model data overlap with placeholders

### ISSUE THREAD

**Issue by anushkamahesh** [mhartington/ion-md-input#6]
Hi, 
I have used ion-md-input for a form, I have per-loaded some values with ng-model. But this thing happens to me, it's overlap with placeholder and values. Is there any way to fix this. 
![screenshot from 2015-07-06 12 05 49](https://cloud.githubusercontent.com/assets/1327120/8516897/d6718910-23d7-11e5-83d2-6f611b825baa.png)

**Comment by mhartington** [comment]
Hmm, is there anyway you could replicate this in a codepen? 
http://codepen.io/mhartington/pen/jPzaQL

**Comment by anushkamahesh** [comment]
Here is codepen example 
http://codepen.io/anushkamahesh/pen/RPMBZz

**Comment by mhartington** [comment]
Looking into this

**Comment by mhartington** [comment]
Should be fixed, bower will take a while to update so you can just pull from here.

**Comment by ljammala** [comment]
I am still having this issue using your latest update.

**Comment by mhartington** [comment]
Please open a new issue and provide a codepen showing the issue.

**Comment by ljammala** [comment]
Sorry, it's resolved now. There was a conflict in the version ionicmaterial.com demo has and the latest you have on https://cdn.rawgit.com/mhartington/ion-md-input/master/js/ion-md-input.js

Thanks!

**Comment by ljammala** [comment]
Even the version on you git is different from https://cdn.rawgit.com/mhartington/ion-md-input/master/js/ion-md-input.js

The work "highlight" is spelled wrong in your git. It is spelled as "hightlight"

**Comment by mhartington** [comment]
If you're pulling from bower, it takes a while for bower to update. It's best to just install right from the source.

**Comment by crmolinaz** [comment]
i resolved the issue with this code:

angular.module('ionMdInput', [])

.directive('ionMdInput', function() {
  return {
    restrict: 'E',
    replace: true,
    require: '?ngModel',
    template: '<label class="item item-input item-md-label">' +
      '<input type="text" class="md-input">' +
      '<span class="input-label"></span>' +
      '<div class="highlight"></div>' +
      '</label>',
    compile: function(element, attr) {

      var highlight = element[0].querySelector('.highlight');
      var highlightColor;
      if (!attr.highlightColor) {
        highlightColor = 'calm';
      } else {
        highlightColor = attr.highlightColor;
      }
      highlight.className += ' highlight-' + highlightColor;

      var label = element[0].querySelector('.input-label');
      label.innerHTML = attr.placeholder;
      
      var _dirty = false;
      if(attr.ngModel || attr.ngValue) {
          _dirty = true;
      }
      console.log(_dirty);
      
      /*Start From here*/
      var input = element.find('input');
      angular.forEach({
        'name': attr.name,
        'type': attr.type,
        'ng-value': attr.ngValue,
        'ng-model': attr.ngModel,
        'required': attr.required,
        'ng-required': attr.ngRequired,
        'ng-minlength': attr.ngMinlength,
        'ng-maxlength': attr.ngMaxlength,
        'ng-pattern': attr.ngPattern,
        'ng-change': attr.ngChange,
        'ng-trim': attr.trim,
        'ng-blur': attr.ngBlur,
        'ng-focus': attr.ngFocus,
      }, function(value, name) {
        if (angular.isDefined(value)) {
          input.attr(name, value);
          if(_dirty === true) {
              input.attr('class', 'used');
          }
        }
      });

      var cleanUp = function() {
        ionic.off('$destroy', cleanUp, element[0]);
      };
      // add listener
      ionic.on('$destroy', cleanUp, element[0]);

      return function LinkingFunction($scope, $element) {

        var mdInput = $element[0].querySelector('.md-input');

        var dirtyClass = 'used';

        var reg = new RegExp('(\\s|^)' + dirtyClass + '(\\s|$)');

        //Here is our toggle function
        var toggleClass = function() {
          if (this.value === '') {
            this.className = mdInput.className.replace(reg, ' ');
          } else {
            this.classList.add(dirtyClass);
          }
        };

        //Lets check if there is a value on load
        ionic.DomUtil.ready(function() {
          if (mdInput.value === '') {
            mdInput.className = mdInput.className.replace(reg, ' ');
          } else {
            mdInput.classList.add(dirtyClass);
          }
        });
        // Here we are saying, on 'blur', call toggleClass, on mdInput
        ionic.on('blur', toggleClass, mdInput);
        ionic.on('change', toggleClass, mdInput);

      };

    }
  };
});

**Comment by crmolinaz** [comment]
i fixed the issue with this code:

var _dirty = false;
      if(attr.ngModel || attr.ngValue) {
          _dirty = true;
      }
      console.log(_dirty);
      
      /*Start From here*/
      var input = element.find('input');
      angular.forEach({
        'name': attr.name,
        'type': attr.type,
        'ng-value': attr.ngValue,
        'ng-model': attr.ngModel,
        'required': attr.required,
        'ng-required': attr.ngRequired,
        'ng-minlength': attr.ngMinlength,
        'ng-maxlength': attr.ngMaxlength,
        'ng-pattern': attr.ngPattern,
        'ng-change': attr.ngChange,
        'ng-trim': attr.trim,
        'ng-blur': attr.ngBlur,
        'ng-focus': attr.ngFocus,
      }, function(value, name) {
        if (angular.isDefined(value)) {
          input.attr(name, value);
          if(_dirty === true) {
              input.attr('class', 'used');
          }
        }
      });
