### ISSUE TITLE
Css not running

### ISSUE THREAD

**Issue by LeoLR** [mhartington/ion-md-input#8]
Hi!

I've some problems with my css, i've the same than your demo but i've this on my app:

![login - google chrome](https://cloud.githubusercontent.com/assets/10087588/8698626/062a5ef0-2b00-11e5-851f-8312235fffe1.jpg)

If you've a idea for fix this? 

Thank's!

**Comment by mhartington** [comment]
Not sure what could be causing this. Could you provide a codepen demo?

**Comment by mhartington** [comment]
Closing this since there has been no reply.
