### ISSUE TITLE
placeholder fall into the input even input has value

### ISSUE THREAD

**Issue by jp928** [mhartington/ion-md-input#9]
On line 68, if using toggle on this.classList.toggle(dirtyClass);  
the issue will occur like the screen shot. Suggest to use add instead of toggle.
![capture](https://cloud.githubusercontent.com/assets/659612/8770110/79bd7e1e-2eee-11e5-8d58-405096a45759.PNG)

**Comment by mhartington** [comment]
Sorry about that, should be fixed now
